### ISSUE TITLE
Detected a blocking call while validating the requests

### ISSUE THREAD

**Issue by rp199** [cdimascio/swagger-spring-functional#27]
After installing the [Blackhound](https://github.com/reactor/BlockHound) on a webflux + kotlin coroutines application using this project as the request validator, noticed that there's a blocking call within an external lib:

Stacktrace:
```
reactor.blockhound.BlockingOperationError: Blocking call! jdk.internal.misc.Unsafe#park
	at java.base/jdk.internal.misc.Unsafe.park(Unsafe.java) ~[na:na]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
(...)
Stack trace:
		at java.base/jdk.internal.misc.Unsafe.park(Unsafe.java) ~[na:na]
		at java.base/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234) ~[na:na]
		at java.base/java.util.concurrent.FutureTask.awaitDone(FutureTask.java:444) ~[na:na]
		at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:203) ~[na:na]
		at com.github.fge.msgsimple.provider.LoadingMessageSourceProvider.getMessageSource(LoadingMessageSourceProvider.java:202) ~[msg-simple-1.1.jar:na]
		at com.github.fge.msgsimple.bundle.MessageBundle.getMessage(MessageBundle.java:122) ~[msg-simple-1.1.jar:na]
		at com.github.fge.msgsimple.bundle.MessageBundle.getMessage(MessageBundle.java:146) ~[msg-simple-1.1.jar:na]
		at com.github.fge.jsonschema.processors.validation.InstanceValidator.<init>(InstanceValidator.java:85) ~[json-schema-validator-2.2.11.jar:na]
		at com.github.fge.jsonschema.processors.validation.ValidationProcessor.process(ValidationProcessor.java:54) ~[json-schema-validator-2.2.11.jar:na]
		at com.github.fge.jsonschema.processors.validation.ValidationProcessor.process(ValidationProcessor.java:34) ~[json-schema-validator-2.2.11.jar:na]
		at com.github.fge.jsonschema.core.processing.ProcessingResult.of(ProcessingResult.java:79) ~[json-schema-core-1.2.10.jar:na]
		at com.github.fge.jsonschema.main.JsonSchemaImpl.doValidate(JsonSchemaImpl.java:77) ~[json-schema-validator-2.2.11.jar:na]
		at com.github.fge.jsonschema.main.JsonSchemaImpl.validate(JsonSchemaImpl.java:100) ~[json-schema-validator-2.2.11.jar:na]
		at com.atlassian.oai.validator.schema.SchemaValidator.validate(SchemaValidator.java:116) ~[swagger-request-validator-core-2.11.0.jar:na]
		at com.atlassian.oai.validator.interaction.request.ParameterValidator.validate(ParameterValidator.java:72) ~[swagger-request-validator-core-2.11.0.jar:na]
		at com.atlassian.oai.validator.interaction.request.RequestValidator.lambda$validateParameter$22(RequestValidator.java:429) ~[swagger-request-validator-core-2.11.0.jar:na]
		at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
		at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654) ~[na:na]
		at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
		at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
		at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[na:na]
		at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
		at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:553) ~[na:na]
		at com.atlassian.oai.validator.interaction.request.RequestValidator.validateParameter(RequestValidator.java:430) ~[swagger-request-validator-core-2.11.0.jar:na]
		at com.atlassian.oai.validator.interaction.request.RequestValidator.lambda$validateHeaders$20(RequestValidator.java:361) ~[swagger-request-validator-core-2.11.0.jar:na]
		at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
		at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[na:na]
		at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654) ~[na:na]
		at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
		at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
		at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[na:na]
		at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
		at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:553) ~[na:na]
		at com.atlassian.oai.validator.interaction.request.RequestValidator.validateHeaders(RequestValidator.java:366) ~[swagger-request-validator-core-2.11.0.jar:na]
		at com.atlassian.oai.validator.interaction.request.RequestValidator.validateRequest(RequestValidator.java:108) ~[swagger-request-validator-core-2.11.0.jar:na]
		at com.atlassian.oai.validator.OpenApiInteractionValidator.lambda$validateRequest$2(OpenApiInteractionValidator.java:196) ~[swagger-request-validator-core-2.11.0.jar:na]
		at java.base/java.util.function.Function.lambda$andThen$1(Function.java:88) ~[na:na]
		at com.atlassian.oai.validator.OpenApiInteractionValidator.validateOnApiOperation(OpenApiInteractionValidator.java:253) ~[swagger-request-validator-core-2.11.0.jar:na]
		at com.atlassian.oai.validator.OpenApiInteractionValidator.validateRequest(OpenApiInteractionValidator.java:193) ~[swagger-request-validator-core-2.11.0.jar:na]
		at io.github.cdimascio.openapi.Validator.validateAndAwait(Validator.kt:39) ~[openapi-spring-webflux-validator-3.3.0.jar:na]
		at io.github.cdimascio.openapi.Validator.validateAndAwait$default(Validator.kt:34) ~[openapi-spring-webflux-validator-3.3.0.jar:na]
		at io.github.cdimascio.openapi.Validate.requestAndAwait(Validate.kt:87) ~[openapi-spring-webflux-validator-3.3.0.jar:na]
```

Not sure about the real impact of this on the actual behaviour of the application, I'd expect that in practice it will be minimal but I'm concerned about having a blocking call on all the inbound requests...

Nevertheless I've decided to flag this because this prevents the library to be fully non blocking.  Not sure also if there's any way to change this within this library since the blocking call is happening on a dependency of a dependency of this project. 

I'd guess that would require to change the whole validator implementation.  

Edit: This is blocking the reactor nio thread and the time out defined for this blocking operation is 1 second:
![image](https://user-images.githubusercontent.com/52860444/112032683-8de3aa00-8b34-11eb-8da4-dab82f18a0b7.png)

**Comment by cdimascio** [comment]
You can use `request` rather than `requestAndAwait`. The latter is the suspended alternative to `request`. 
The following doc is useful when composing suspending functions https://kotlinlang.org/docs/composing-suspending-functions.html

closing out

**Comment by rp199** [comment]
@cdimascio thanks for the reply. 

I think this issue can be closed anyway as the blocking call does not cause any impact on the application, but I’m a little bit confused by your reply as it doesn’t seem related with the reported topic.

How can using the `request` avoid the blocking call?

**Comment by cdimascio** [comment]
I see. task.get() blocks. Yes that is not easy to overcome. That said It should be very quick
